spring.application.name=planning-app

# DB persistante (fichier)
spring.datasource.url=jdbc:h2:file:./data/planningdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# Console H2
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Remplace "never" par "always"
spring.sql.init.mode=always

# Ajoute cette ligne pour que JPA crée les tables AVANT data.sql
spring.jpa.defer-datasource-initialization=true

spring.sql.init.encoding=UTF-8

server.port=${PORT:8080}