spring.application.name=planning-app

# PostgreSQL - Render
spring.datasource.url=jdbc:postgresql://dpg-d7u8c367r5hc73bfjq10-a:5432/planning_db_asaj
spring.datasource.username=planning_db_asaj_user
spring.datasource.password=aOG8qAB1TJTEkXXNKAOUemCje4NbZj42
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.defer-datasource-initialization=true

# SQL init
spring.sql.init.mode=always
spring.sql.init.encoding=UTF-8

server.port=${PORT:8080}