spring.application.name=planning-app

# DB persistante (fichier)
spring.datasource.url=jdbc:h2:file:./data/planningdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# Console H2
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Ne jamais rejouer data.sql au démarrage
spring.sql.init.mode=never

server.port=${PORT:8080}